export const siteConfig = {
  name: "KIMORI",
  brandLine: "木森 · A Serene Ascent Above Serdang",
  title: "KIMORI Serdang | New Freehold Development Project, Bukit Serdang",
  description:
    "KIMORI Residences is a new freehold condominium development project in Bukit Serdang, Seri Kembangan, by Premierex Development: 418 units, 34 facilities, KLCC views, 3 km to MRT UPM.",
  url: "https://www.kimoriresidences.com",
  homeUrl: "https://www.kimoriresidences.com/",
  developer: "Premierex Development",
  locale: "en_MY",
  phone: "+60 12-375 6880",
  whatsapp: "60123756880",
  address: {
    street: "No. LG69-70, Jalan BS 1/2, Bukit Serdang",
    postal: "43300",
    locality: "Seri Kembangan",
    region: "Selangor",
    country: "Malaysia",
  },
  tour360: "https://www.7degree.com.my/360VR/Kimori/",
  tour360TypeA: "https://www.7degree.com.my/360VR/Kimori/",
  tour360TypeB: "https://my.treedis.com/tour/kimori-residences-type-b",
  keywords: [
    "Kimori",
    "Kimori Residences",
    "Kimori Serdang",
    "Kimori Bukit Serdang",
    "Serdang project",
    "Serdang new project",
    "Serdang development project",
    "new development in Serdang",
    "new property project in Serdang",
    "Bukit Serdang project",
    "Bukit Serdang new project",
    "Bukit Serdang new launch",
    "Bukit Serdang condominium",
    "Bukit Serdang condo",
    "Bukit Serdang freehold",
    "Serdang condo",
    "Serdang condominium",
    "Serdang freehold condo",
    "Serdang new launch",
    "Seri Kembangan project",
    "Seri Kembangan new launch",
    "Seri Kembangan condominium",
    "Seri Kembangan freehold",
    "freehold condominium Selangor",
    "new condominium Selangor",
    "Selangor new launch 2026",
    "Premierex Development",
    "Premierex Serdang",
    "Japanese design condominium Malaysia",
    "Japanese-inspired condominium Malaysia",
    "KLCC view condominium",
    "KLCC view condo Serdang",
    "MRT UPM condominium",
    "UPM new launch",
    "Klang Valley freehold condominium",
  ],
};

export type SiteConfig = typeof siteConfig;
